import numpy as np
import matplotlib.pyplot as plt
def s(x):
    a=np.where(x==0,1,np.sin(x)/x)
    return a
x=np.linspace(0,10,100)
y=np.exp(x)
t=np.linspace(-10,10,100)
z=s(t)
fig=plt.figure()
plt.subplot(2,2,1)
plt.plot(x,y)
plt.xlabel(r'Time (ms)', fontsize=14)
plt.ylabel(r'Distance (mm)', fontsize=14)
plt.axhline(color='gray')
plt.axvline(color='gray')
plt.subplot(2,2,2)
plt.semilogy(x,y)   
plt.xlabel(r'Time (ms)', fontsize=14)
plt.ylabel(r'Distance (mm)', fontsize=14)
plt.axhline(color='gray')
plt.axvline(color='gray')
plt.subplot(2,1,2)
plt.plot(t,z)
plt.xlabel(r"x", fontsize=14)
plt.ylabel(r"sinc(x)",fontsize=14)
plt.axhline(color='gray')
plt.axvline(color='gray')
fig.tight_layout()
plt.show()